name: airbnb_months_picker
description: "Airbnb Months Picker"
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  tactile_feedback:
    git: https://github.com/ksokolovskyi/tactile_feedback

dev_dependencies:
  very_good_analysis: ^10.0.0

flutter:
  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Bold.ttf
          weight: 700
